import './style.css'
import { module3Topics, module3QuestionCount } from './practice3.js'

const transferPyqs=[
 {year:'2024',q:'Q41',title:'Sequence reversal · transfer',answer:'Option C',question:'fun(D,s1,s2) swaps endpoints and recursively moves boundaries inward while s1<s2. What does it do?',options:['A. Find minimum','B. Merge sort','C. Reverse inclusive segment','D. Only one swap'],steps:'First-last, second-second-last… pairs swap until center. Mutable list segment reverses in-place.',trap:'String par same assignment possible nahi because string immutable; string solution compare/two-pointer ya new string use karega.',pattern:'Palindrome/reversal ke symmetric-index reasoning mein direct transfer.'},
 {year:'2025',q:'Q23',title:'Method semantics · transfer',answer:'Option A',question:'A=[1,2,3], B=[4,5,6]. Which statement makes A=[1,2,3,4,5,6]?',options:['A. A.extend(B)','B. A.append(B)','C. A.update(B)','D. A.insert(B)'],steps:'extend iterable elements add karta hai; append argument ko one object banata hai.',trap:'String methods list methods ki tarah in-place mutate nahi karte; return capture karna hota hai.',pattern:'Method name se zyada input/output type aur final shape trace karo.'},
 {year:'2026',q:'Q16',title:'Mutability contrast · transfer',answer:'Option B',question:'Function default list [] mein values append karta hai. Calls (1), (2), then (3,[]) ka output?',options:['A. [1],[2],[3]','B. [1],[1,2],[3]','C. [1],[2],[1,2,3]','D. [1],[1,2],[1,3]'],steps:'Default mutable list once create aur first two calls reuse. Explicit [] fresh object.',trap:'String default immutable hota toh concatenation name ko rebind karti; shared object mutate nahi hota.',pattern:'Object mutability ko function-call state ke saath combine karo.'}
]
const pyqMarkup=transferPyqs.map(x=>`<details class="pyq-card searchable" data-year="${x.year}"><summary><span class="year">${x.year}</span><span><b>${x.q} · ${x.title}</b><small>Not direct string PYQ · concept transfer</small></span><i>＋</i></summary><div class="pyq-body"><div class="answer"><span>Correct answer</span><strong>${x.answer}</strong></div><div class="pyq-question"><h4>Original question · clean transcript</h4><p>${x.question}</p><ul>${x.options.map(o=>`<li>${o}</li>`).join('')}</ul></div><div><h4>Step-by-step reasoning</h4><p>${x.steps}</p></div><aside><strong>String-specific caution</strong><p>${x.trap}</p></aside><aside class="transfer"><strong>Reusable pattern</strong><p>${x.pattern}</p></aside></div></details>`).join('')
const topicOptions=module3Topics.map(t=>`<option value="${t.id}">${t.number} · ${t.label} (${t.questions.length})</option>`).join('')
const chapterHead=(n,label,title,sub)=>`<div class="chapter-head"><div class="chapter-no"><span>${n}</span><small>${label}</small></div><div><h2>${title}</h2><p>${sub}</p></div></div>`

document.querySelector('#app').innerHTML=`
<div class="read-progress"><span></span></div><header class="topbar"><a class="brand" href="#top"><b>DA</b><span><strong>Python + DSA</strong><small>GATE 2027 Notebook</small></span></a><nav><button class="tab active" data-view="notes">Detailed Notes</button><button class="tab" data-view="pyq">PYQ Evidence <i>0+3</i></button><button class="tab" data-view="practice">Practice <i>${module3QuestionCount}</i></button><button class="tab" data-view="revision">Revision</button></nav><div class="actions"><button id="searchButton" aria-label="Search">⌕</button><button id="themeButton" aria-label="Theme">◐</button></div></header>
<div class="searchbox"><input id="search" type="search" placeholder="Search: immutable, strip, anagram, palindrome…"><span id="searchResult">Search current view</span></div>
<div class="layout" id="top"><aside class="sidebar"><p class="overline">Module 03</p><h2>Strings</h2><div class="module-switch"><a href="./index.html">M01</a><a href="./module2.html">M02</a><a class="active" href="./module3.html">M03</a><a href="./module4.html">M04</a><a href="./module5.html">M05</a><a href="./module6.html">M06</a></div><div class="completion"><span><b>Lecture progress</b><i id="count">0/11</i></span><div><i id="bar"></i></div></div><nav id="toc"></nav><p class="source"><b>Sources</b>CampusX PDF + four string notebooks + GATE DA 2024–2026 papers</p></aside><main>
<div class="view active" data-panel="notes">
  <section class="hero module3-hero searchable" data-title="Overview"><p class="eyebrow"><i></i> Module 03 · text as a sequence</p><h1>Characters nahi—<em>rules wali sequence</em> dekho.</h1><p>String questions indexing, immutability, Unicode comparison, normalization aur frequency/window invariants test karte hain.</p><div class="metrics"><span><b>0</b>direct DA string PYQs</span><span><b>3</b>transfer PYQs</span><span><b>${module3QuestionCount}</b>practice drills</span></div><div class="syllabus"><b>2027 syllabus map</b>Programming in Python · sequence tracing · foundation for text processing and hashing</div></section>

  <section class="lecture-track searchable" id="lecture-track" data-title="Module 3 lecture tracker"><div class="track-head"><div><p class="eyebrow"><i></i> CampusX + GATE bridge</p><h2>Module 3 · Lecture Tracker</h2><p>Original lecture flow preserve hai; missing exam concepts orange bridge blocks mein hain.</p></div><strong id="lecturePercent">0%</strong></div><div class="lecture-list">
    <label><input type="checkbox" data-lecture="3.1"><span><b>3.1</b><i>Introduction</i><small>Creation and indexing</small></span></label><label><input type="checkbox" data-lecture="3.2"><span><b>3.2</b><i>Properties</i><small>Immutable, iterable, slicing</small></span></label><label><input type="checkbox" data-lecture="3.2A"><span><b>3.2A</b><i>Unicode</i><small>ord, chr, encoding</small></span></label><label><input type="checkbox" data-lecture="3.3"><span><b>3.3</b><i>Use cases</i><small>Text, algorithms, NLP</small></span></label><label><input type="checkbox" data-lecture="3.4"><span><b>3.4</b><i>Common functions</i><small>Core method map</small></span></label><label><input type="checkbox" data-lecture="3.5A"><span><b>3.5A</b><i>Case & whitespace</i><small>Normalize carefully</small></span></label><label><input type="checkbox" data-lecture="3.5B"><span><b>3.5B</b><i>Search & validation</i><small>find/index and is*</small></span></label><label><input type="checkbox" data-lecture="3.5C"><span><b>3.5C</b><i>Split, join, replace</i><small>Transformations</small></span></label><label><input type="checkbox" data-lecture="3.6"><span><b>3.6</b><i>Comparison</i><small>Lexicographic order</small></span></label><label><input type="checkbox" data-lecture="3.7"><span><b>3.7</b><i>Coding problems</i><small>Frequency, palindrome, anagram</small></span></label><label><input type="checkbox" data-lecture="3.8"><span><b>3.8</b><i>DS context + patterns</i><small>Substring and window</small></span></label>
  </div></section>

  <section class="beginner-start searchable" id="zero-start" data-title="Zero-start mental model"><div class="zero-title"><span>ZERO START</span><h2>String ko characters ki immutable row samjho.</h2><p>Index character ki position hai. Method chalne par old row edit nahi hoti—usually ek nayi string milti hai.</p></div><div class="glossary-grid"><article><b>Character</b><p>One Unicode text unit, Python indexing par one-character <code>str</code>.</p></article><article><b>Substring</b><p>Original string ka contiguous portion.</p></article><article><b>Prefix</b><p>Beginning se continuous substring.</p></article><article><b>Suffix</b><p>End par finish hone wala substring.</p></article><article><b>Normalize</b><p>Comparison se pehle agreed case/spacing policy.</p></article><article><b>Immutable</b><p>Existing string contents modify nahi ho sakte.</p></article></div><div class="reading-method"><h3>Question reading order</h3><div><span><b>1</b>Raw text</span><span><b>2</b>Index/slice</span><span><b>3</b>New string?</span><span><b>4</b>Normalization</span></div></div></section>

  <section class="chapter searchable" id="intro" data-title="3.1 · Introduction">${chapterHead('3.1','INTRODUCTION','String kya hai?','Single, double aur triple quotes sirf creation syntax hain.')}
    <div class="two-grid"><article><h3>Ordered sequence</h3><p><code>s='GATE'</code>: indices 0,1,2,3 and negative indices −4…−1. <code>s[0]</code> one-character string <code>'G'</code>.</p></article><article><h3>Creation</h3><p>Single/double quotes normal literals; triple quotes multi-line text/docstrings; escapes quote/newline represent karte hain.</p></article></div><div class="codebox"><div><span>Index map</span><button>Copy</button></div><pre><code>s = 'GATE'
# positive:  0  1  2  3
# chars:     G  A  T  E
# negative: -4 -3 -2 -1
print(s[0], s[-1])  # G E</code></pre></div><div class="danger"><b>Type trap</b><p><code>'123'[0]</code> ka result <code>'1'</code> string hai, integer 1 nahi.</p></div>
  </section>

  <section class="chapter searchable" id="properties" data-title="3.2 · Properties and slicing">${chapterHead('3.2','PROPERTIES','Immutable ka real meaning','Rebinding aur mutation ko separate rakho.')}
    <div class="code-grid"><div class="codebox red"><div><span>Not allowed</span><button>Copy</button></div><pre><code>s = 'hello'
s[0] = 'H'   # TypeError</code></pre></div><div class="codebox green"><div><span>Create new</span><button>Copy</button></div><pre><code>s = 'hello'
s = 'H' + s[1:]
# old object edit nahi; name rebound</code></pre></div></div><div class="equation"><span>slice</span><b>s[start : stop : step] · stop excluded</b></div><div class="table-wrap"><table><thead><tr><th>Operation</th><th>Time</th><th>Space</th></tr></thead><tbody><tr><td><code>len(s), s[i]</code></td><td>O(1)</td><td>O(1)</td></tr><tr><td><code>s[a:b]</code> length k</td><td>O(k)</td><td>O(k)</td></tr><tr><td><code>for ch in s</code></td><td>O(n)</td><td>O(1)</td></tr><tr><td><code>s+t</code></td><td>O(n+m)</td><td>O(n+m)</td></tr><tr><td><code>s[::-1]</code></td><td>O(n)</td><td>O(n)</td></tr></tbody></table></div><div class="danger"><b>GATE complexity trap</b><p>Growing string ko loop mein <code>result += ch</code> karna worst O(n²) ho sakta hai. Chunks list mein collect karke <code>''.join(chunks)</code> use karo.</p></div>
  </section>

  <section class="chapter searchable" id="unicode-compare" data-title="3.2 · Unicode and encoding">${chapterHead('3.2A','CORRECTION','Unicode character ≠ UTF-8 byte','Lecture statement ko precise banane wala important bridge.')}
    <div class="two-grid"><article><h3><code>str</code></h3><p>Unicode text abstraction. <code>ord(ch)</code> code point integer; <code>chr(n)</code> character.</p></article><article><h3><code>bytes</code></h3><p>Encoding ke baad raw bytes: <code>s.encode('utf-8')</code>. Decode bytes ko text banata hai.</p></article></div><div class="callout"><b>Correction</b><p>“Python strings UTF-8 mein internally stored hain” universal semantic guarantee nahi. Python <code>str</code> Unicode sequence hai; UTF-8 ek external encoding choice hai.</p></div><div class="codebox"><div><span>Code point vs encoding</span><button>Copy</button></div><pre><code>ord('A')              # 65
chr(65)               # 'A'
'é'.encode('utf-8')    # two UTF-8 bytes
len('é')               # 1 Python character</code></pre></div>
  </section>

  <section class="chapter searchable" id="usecases" data-title="3.3 · Use cases">${chapterHead('3.3','WHY STRINGS','Text se algorithms tak','Use case se required normalization aur data structure decide hota hai.')}
    <div class="three-grid"><article><span>Programs</span><h3>Names, logs, paths</h3><p>Parsing, cleaning and validation.</p></article><article><span>Algorithms</span><h3>Search and hashing</h3><p>Substring matching, rolling hash, frequency windows.</p></article><article><span>Data science</span><h3>NLP pipeline</h3><p>Tokenization, features, sentiment, model inputs.</p></article></div><div class="danger"><b>Never normalize blindly</b><p>Password, identifier aur natural-language sentence ki case/space rules same nahi. Problem specification pehle padho.</p></div>
  </section>

  <section class="chapter searchable" id="common" data-title="3.4 · Common functions">${chapterHead('3.4','FUNCTION MAP','Method kya return karta hai?','Strings immutable hain: methods ka result capture karo.')}
    <div class="table-wrap"><table><thead><tr><th>Method</th><th>Result</th><th>Missing/edge</th></tr></thead><tbody><tr><td><code>lower/upper</code></td><td>new cased string</td><td>original unchanged</td></tr><tr><td><code>strip</code></td><td>ends cleaned</td><td>not internal whitespace</td></tr><tr><td><code>replace</code></td><td>new replaced string</td><td>optional count</td></tr><tr><td><code>split</code></td><td>list of strings</td><td>default vs explicit sep differ</td></tr><tr><td><code>sep.join(it)</code></td><td>one string</td><td>items must be strings</td></tr><tr><td><code>find</code></td><td>first index</td><td>−1 if absent</td></tr><tr><td><code>index</code></td><td>first index</td><td>ValueError if absent</td></tr><tr><td><code>count</code></td><td>non-overlap count</td><td>overlaps not counted</td></tr></tbody></table></div><div class="danger"><b>Sentinel trap</b><p><code>if s.find(x):</code> wrong ho sakta hai: index 0 falsy aur −1 truthy. Use <code>if x in s</code> or <code>if s.find(x) != -1</code>.</p></div>
  </section>

  <section class="chapter searchable" id="case-space" data-title="3.5 · Case and whitespace">${chapterHead('3.5A','MANIPULATION','Cleaning ka rule exact rakho','strip argument substring nahi, character set jaisa behave karta hai.')}
    <div class="two-grid"><div><h3>Case</h3><p><code>lower</code>, <code>upper</code>, <code>title</code>, <code>capitalize</code>, <code>swapcase</code>. Caseless Unicode matching mein <code>casefold</code> stronger option.</p></div><div><h3>Whitespace</h3><p><code>strip</code> both ends; <code>lstrip</code>/<code>rstrip</code> one side. Internal runs normalize karne ke liye <code>' '.join(s.split())</code>.</p></div></div><div class="codebox"><div><span>strip character-set trap</span><button>Copy</button></div><pre><code>'www.example.com'.strip('w.')
# 'example.com'
# exact prefix 'www.' remove command nahi;
# ends se w or . repeatedly remove</code></pre></div>
  </section>

  <section class="chapter searchable" id="search-validate" data-title="3.5 · Search and validation">${chapterHead('3.5B','CHECKS','Boolean method ke hidden conditions','Empty string aur no-cased-character cases important hain.')}
    <div class="table-wrap"><table><thead><tr><th>Check</th><th>True when</th><th>Key edge</th></tr></thead><tbody><tr><td><code>isalpha</code></td><td>all alphabetic</td><td>empty false</td></tr><tr><td><code>isdigit</code></td><td>all digit chars</td><td>not integer conversion</td></tr><tr><td><code>isalnum</code></td><td>letters/digits</td><td>space false</td></tr><tr><td><code>isspace</code></td><td>all whitespace</td><td>non-empty required</td></tr><tr><td><code>islower/isupper</code></td><td>all cased chars match</td><td>one cased char required</td></tr><tr><td><code>startswith/endswith</code></td><td>prefix/suffix match</td><td>tuple alternatives allowed</td></tr></tbody></table></div><div class="callout"><b>Substring cost</b><p>Naive pattern length m ko text length n mein search worst O(nm). Built-in implementation optimized ho sakta hai, but exam mein specified algorithm analyze karo.</p></div>
  </section>

  <section class="chapter searchable" id="split-join" data-title="3.5 · Split, join, replace and formatting">${chapterHead('3.5C','TRANSFORM','Type flow draw karo','str → list[str] → str ek common pipeline hai.')}
    <div class="trace-flow"><span><b>raw string</b><code>'a  b'</code></span><i>split()</i><span><b>tokens</b><code>['a','b']</code></span><i>join</i><span><b>normalized</b><code>'a b'</code></span></div><div class="two-grid"><article><h3>Default split</h3><p>Whitespace runs collapse, leading/trailing ignore. <code>'a  b'.split() → ['a','b']</code>.</p></article><article><h3>Explicit separator</h3><p>Adjacent separators empty token bana sakte: <code>'a  b'.split(' ') → ['a','','b']</code>.</p></article></div><div class="danger"><b>join direction</b><p><code>'-'.join(parts)</code> correct hai, <code>parts.join('-')</code> nahi. Non-string items ko pehle <code>map(str,...)</code>.</p></div>
  </section>

  <section class="chapter searchable" id="comparison" data-title="3.6 · String comparison">${chapterHead('3.6','LEXICOGRAPHIC','Dictionary-like, but Unicode-aware','First differing code point decision karta hai.')}
    <div class="steps"><article><b>1</b><h3>Left to right</h3><p>Same-position chars compare.</p></article><article><b>2</b><h3>First mismatch</h3><p>Unicode code points decide.</p></article><article><b>3</b><h3>Prefix tie</h3><p>Shorter string smaller.</p></article><article><b>4</b><h3>Case</h3><p>Raw comparison sensitive.</p></article><article><b>5</b><h3>Normalize?</h3><p>Only if specification says.</p></article></div><div class="codebox"><div><span>Classic traps</span><button>Copy</button></div><pre><code>'10' < '2'       # True: '1' < '2'
'Zoo' < 'apple'  # True: ord('Z') < ord('a')
'ball' < 'balls' # True: shorter common prefix</code></pre></div>
  </section>

  <section class="chapter searchable" id="coding" data-title="3.7 · Coding problems">${chapterHead('3.7','LECTURE PROBLEMS','Frequency se palindrome/anagram tak','Assumptions, correctness invariant aur cost sab mention karo.')}
    <div class="practice-list"><article><span>01</span><div><b>Vowels/consonants</b><p><code>isalpha</code> filter; case normalize; special chars ignore.</p></div><strong>O(n) · O(1)*</strong></article><article><span>02</span><div><b>Character frequency</b><p><code>d[ch]=d.get(ch,0)+1</code>. Empty-dict notebook bug corrected.</p></div><strong>O(n) expected</strong></article><article><span>03</span><div><b>Palindrome</b><p>Slice simple O(n) space; two pointers O(1) auxiliary.</p></div><strong>Symmetric pairs</strong></article><article><span>04</span><div><b>Anagram</b><p>Sort O(n log n); frequency map O(n) expected; 26-array only lowercase constraint.</p></div><strong>Counts invariant</strong></article></div>
    <div class="code-grid"><div class="codebox green"><div><span>Palindrome · O(1) aux</span><button>Copy</button></div><pre><code>def palindrome(s):
    left, right = 0, len(s)-1
    while left < right:
        if s[left] != s[right]: return False
        left += 1; right -= 1
    return True</code></pre></div><div class="codebox"><div><span>Anagram · general chars</span><button>Copy</button></div><pre><code>from collections import Counter
def anagram(a, b):
    return len(a) == len(b) and Counter(a) == Counter(b)</code></pre></div></div><small>*Fixed alphabet relative to input size; dictionary version O(k) distinct characters space.</small>
  </section>

  <section class="chapter searchable" id="substring-window" data-title="3.8 · Substring and window bridge">${chapterHead('3.8','GATE ADD-ON','Substring contiguous hota hai','Lecture ke future KMP/hash references se pehle essential counting/window base.')}
    <div class="danger"><b>Priority label</b><p><b>Useful problem-solving pattern, lower priority for official GATE DA DSA syllabus.</b> GATE core ke liye immutability, slicing, comparison, split/join aur operation costs first priority hain.</p></div>
    <div class="two-grid"><article><h3>Substring</h3><p>Contiguous: <code>'ate'</code> in <code>'gate'</code>. Non-empty substrings count n(n+1)/2. Subsequence characters skip kar sakti hai.</p></article><article><h3>Character window</h3><p>Fixed-k anagram/search window mein outgoing count decrement, incoming increment. All windows O(n) with fixed alphabet.</p></article></div><div class="codebox"><div><span>Longest unique substring pattern</span><button>Copy</button></div><pre><code>left = 0
last = {}
best = 0
for right, ch in enumerate(s):
    if ch in last and last[ch] >= left:
        left = last[ch] + 1
    last[ch] = right
    best = max(best, right-left+1)</code></pre></div><div class="danger"><b>Output-size analysis</b><p>O(n²) substrings exist. Agar har substring copy/materialize karoge, total copied characters O(n³) tak ho sakte hain.</p></div>
  </section>

  <section class="chapter searchable" id="protocol" data-title="GATE solving protocol">${chapterHead('GATE','FINAL CHECK','String question ka six-step protocol','Normalization assume karne se pehle statement padho.')}
    <div class="steps"><article><b>1</b><h3>Length/index</h3><p>Map positions.</p></article><article><b>2</b><h3>Slice</h3><p>Stop excluded.</p></article><article><b>3</b><h3>Immutability</h3><p>New object/return?</p></article><article><b>4</b><h3>Normalize</h3><p>Only specified rules.</p></article><article><b>5</b><h3>Invariant</h3><p>Counts/window/pairs.</p></article></div><div class="final"><h3>Module 3 mastery</h3><p>Bina run kiye method output type, exact string, edge behavior aur time-space cost derive kar sako.</p><button data-jump="practice">Practice Lab open karo →</button></div>
  </section>
</div>

<div class="view" data-panel="pyq"><section class="page-hero searchable" data-title="Evidence summary"><p class="eyebrow"><i></i> Honest paper analysis</p><h1>PYQ Evidence</h1><p>GATE DA 2024–2026 mein direct string-specific question nahi mila. Neeche ke cards real PYQs hain, lekin explicitly “concept transfer” label ke saath.</p><div class="paper-grid"><span><b>0</b>direct string PYQs</span><span><b>3</b>transfer questions</span><span><b>No fake</b>PYQ labelling</span></div></section><section class="trend searchable" data-title="What to infer"><h2>Zero PYQ ka matlab zero priority nahi</h2><div><p><span>Python semantics</span><i style="--w:100%"></i><b>Every year</b></p><p><span>Sequence tracing</span><i style="--w:88%"></i><b>Transferable</b></p><p><span>Mutation contrast</span><i style="--w:78%"></i><b>High value</b></p><p><span>Direct strings</span><i style="--w:0%"></i><b>Not yet seen</b></p></div><small>Only three DA papers exist, so absence weak evidence hai—not guarantee for 2027.</small></section><div class="filters"><button class="filter active" data-year="all">All transfer PYQs</button><button class="filter" data-year="2024">2024</button><button class="filter" data-year="2025">2025</button><button class="filter" data-year="2026">2026</button><button id="expand">Expand all</button></div><section class="pyqs">${pyqMarkup}</section></div>

<div class="view" data-panel="practice"><section class="page-hero practice-head searchable" data-title="Practice Lab"><p class="eyebrow"><i></i> Topic-wise · saved progress</p><h1>Module 3 Practice</h1><p>${module3QuestionCount} distinct drills; direct PYQ gap ko concept-focused practice se cover karo.</p><div class="practice-summary"><span><b>${module3Topics.length}</b>topic sets</span><span><b>no filler</b>concept variations</span><span><b>saved</b>attempt progress</span></div></section><section class="practice-controls searchable" data-title="Choose topic"><div><label for="practiceTopic">Lecture topic</label><select id="practiceTopic">${topicOptions}</select></div><div><label for="practiceDifficulty">Difficulty</label><select id="practiceDifficulty"><option value="all">All levels</option><option>Foundation</option><option>Core</option><option>Practice</option></select></div><div class="practice-score"><span>Attempted</span><b id="practiceScore">0/0</b></div></section><section class="practice-context" id="practiceContext"></section><section class="question-list" id="questionList"></section></div>

<div class="view" data-panel="revision"><section class="page-hero revision-head searchable" data-title="Revision sheet"><p class="eyebrow"><i></i> Last-day recall</p><h1>Module 3 Revision</h1><p>Semantics, traps and patterns in one sheet.</p><button id="print">Print sheet</button></section><section class="revision-grid"><article class="rev"><span>01</span><h2>Core</h2><ul><li>ordered immutable Unicode sequence</li><li>index gives str</li><li>slice stop excluded</li><li>negative indices from end</li></ul></article><article class="rev"><span>02</span><h2>Returns</h2><ul><li>methods do not mutate original</li><li>split → list[str]</li><li>join → str</li><li>find absent −1</li><li>index absent ValueError</li></ul></article><article class="rev"><span>03</span><h2>Complexity</h2><ul><li>index/len O(1)</li><li>slice k O(k)</li><li>concat O(n+m)</li><li>repeated += can O(n²)</li><li>join chunks preferred</li></ul></article><article class="rev"><span>04</span><h2>Compare</h2><ul><li>first differing code point</li><li>shorter common prefix smaller</li><li>raw case-sensitive</li><li>'10' &lt; '2'</li></ul></article><article class="rev"><span>05</span><h2>Patterns</h2><ul><li>frequency map O(n) expected</li><li>palindrome two pointers</li><li>anagram counts invariant</li><li>fixed window outgoing/incoming</li></ul></article><article class="rev warning"><span>06</span><h2>Never assume</h2><ul><li>UTF-8 bytes = Python chars</li><li>strip removes exact substring</li><li>count finds overlaps</li><li>find can be used raw as bool</li><li>normalize without specification</li></ul></article></section></div>
</main></div><button class="menu" id="menu">☰</button><div class="toast">Copied</div>`

const tabs=[...document.querySelectorAll('.tab')],panels=[...document.querySelectorAll('[data-panel]')],toc=document.querySelector('#toc'),sidebar=document.querySelector('.sidebar')
function buildToc(view){const sections=[...document.querySelector(`[data-panel="${view}"]`).querySelectorAll('[data-title]')];toc.innerHTML=sections.map((s,i)=>{if(!s.id)s.id=`${view}-${i}`;return `<a href="#${s.id}"><i>${String(i+1).padStart(2,'0')}</i>${s.dataset.title}</a>`}).join('')}
function clearSearch(){document.querySelector('#search').value='';document.querySelectorAll('.searchable,.pyq-card').forEach(x=>x.classList.remove('hidden'));document.querySelector('#searchResult').textContent='Search current view'}
function setView(view){tabs.forEach(t=>t.classList.toggle('active',t.dataset.view===view));panels.forEach(p=>p.classList.toggle('active',p.dataset.panel===view));buildToc(view);window.scrollTo({top:0,behavior:'smooth'});clearSearch()}
tabs.forEach(t=>t.onclick=()=>setView(t.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));buildToc('notes')
document.querySelector('#themeButton').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('da-theme',document.documentElement.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('da-theme')!=='light')document.documentElement.classList.add('dark')
if(!document.querySelector('.module-switch a[href="./module7.html"]'))document.querySelector('.module-switch').insertAdjacentHTML('beforeend','<a href="./module7.html">M07</a>')
if(!document.querySelector('.module-switch a[href="./module8.html"]'))document.querySelector('.module-switch').insertAdjacentHTML('beforeend','<a href="./module8.html">M08</a>')
document.querySelector('#searchButton').onclick=()=>{document.querySelector('.searchbox').classList.toggle('open');document.querySelector('#search').focus()};document.querySelector('#search').oninput=e=>{const term=e.target.value.toLowerCase().trim(),items=[...document.querySelector('.view.active').querySelectorAll('.searchable,.pyq-card')];let n=0;items.forEach(x=>{const hit=!term||x.textContent.toLowerCase().includes(term);x.classList.toggle('hidden',!hit);if(hit)n++});document.querySelector('#searchResult').textContent=term?`${n} matching blocks`:'Search current view'}
document.querySelectorAll('.codebox button').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.closest('.codebox').querySelector('code').innerText);const t=document.querySelector('.toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1000)});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pyq-card').forEach(x=>x.classList.toggle('filtered',b.dataset.year!=='all'&&x.dataset.year!==b.dataset.year))});let open=false;document.querySelector('#expand').onclick=e=>{open=!open;document.querySelectorAll('.pyq-card:not(.filtered)').forEach(x=>x.open=open);e.target.textContent=open?'Collapse all':'Expand all'}
const lectureChecks=[...document.querySelectorAll('[data-lecture]')],savedLectures=JSON.parse(localStorage.getItem('da-m3-lectures')||'[]');lectureChecks.forEach(c=>{c.checked=savedLectures.includes(c.dataset.lecture);c.onchange=lectureProgress});function lectureProgress(){const done=lectureChecks.filter(c=>c.checked).map(c=>c.dataset.lecture),percent=Math.round(done.length/lectureChecks.length*100);localStorage.setItem('da-m3-lectures',JSON.stringify(done));document.querySelector('#count').textContent=`${done.length}/${lectureChecks.length}`;document.querySelector('#bar').style.width=`${percent}%`;document.querySelector('#lecturePercent').textContent=`${percent}%`}lectureProgress()
const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')
const attempted=new Set(JSON.parse(localStorage.getItem('da-m3-practice')||'[]')),practiceTopic=document.querySelector('#practiceTopic'),practiceDifficulty=document.querySelector('#practiceDifficulty');function renderPractice(){const topic=module3Topics.find(t=>t.id===practiceTopic.value)||module3Topics[0],level=practiceDifficulty.value,visible=level==='all'?topic.questions:topic.questions.filter(x=>x.difficulty===level),done=topic.questions.filter(x=>attempted.has(x.id)).length,patterns=[...new Set(topic.questions.map(x=>x.pattern))];document.querySelector('#practiceScore').textContent=`${done}/${topic.questions.length}`;document.querySelector('#practiceContext').innerHTML=`<div><span>Topic ${esc(topic.number)}</span><h2>${esc(topic.label)}</h2><p>Exact output paper par derive karo. Explanation tab kholo jab answer lock kar chuke ho.</p></div><aside><b>${visible.length} shown</b><small>${patterns.length} patterns</small><p>${patterns.map(esc).join(' · ')}</p></aside>`;document.querySelector('#questionList').innerHTML=visible.length?visible.map(x=>`<article class="practice-question searchable ${attempted.has(x.id)?'attempted':''}" data-title="${esc(topic.label)} question ${x.number}"><div class="question-meta"><span>Q${String(x.number).padStart(2,'0')}</span><i>${esc(x.difficulty)}</i><b>${esc(x.pattern)}</b></div><h3>${esc(x.prompt)}</h3><ol class="question-options" type="A">${x.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><details class="answer-reveal"><summary>Answer + explanation dekho</summary><div><strong>Correct: ${esc(x.answer)}</strong><p>${x.explanation}</p><small>Rule ko ek fresh string par apply karo.</small></div></details><label class="attempt-check"><input type="checkbox" data-attempt="${x.id}" ${attempted.has(x.id)?'checked':''}><span>Attempted</span></label></article>`).join(''):'<article class="practice-question"><h3>Is difficulty ke questions nahi hain. All levels choose karo.</h3></article>';document.querySelectorAll('[data-attempt]').forEach(box=>box.onchange=()=>{box.checked?attempted.add(box.dataset.attempt):attempted.delete(box.dataset.attempt);localStorage.setItem('da-m3-practice',JSON.stringify([...attempted]));box.closest('.practice-question').classList.toggle('attempted',box.checked);document.querySelector('#practiceScore').textContent=`${topic.questions.filter(x=>attempted.has(x.id)).length}/${topic.questions.length}`})}practiceTopic.onchange=renderPractice;practiceDifficulty.onchange=renderPractice;renderPractice()
const sectionMap={intro:'intro',properties:'properties','unicode-compare':'unicode-compare',comparison:'unicode-compare',common:'common','case-space':'case-space','search-validate':'search-validate','split-join':'split-join',coding:'frequency','substring-window':'substring-window'};Object.entries(sectionMap).forEach(([id,topicId])=>{const section=document.querySelector(`#${id}`),topic=module3Topics.find(t=>t.id===topicId);section.insertAdjacentHTML('beforeend',`<button class="topic-practice" data-practice-topic="${topicId}">Is topic ke ${topic.questions.length} questions solve karo →</button>`)});['palindrome','anagram'].forEach(topicId=>{const topic=module3Topics.find(t=>t.id===topicId);document.querySelector('#coding').insertAdjacentHTML('beforeend',`<button class="topic-practice" data-practice-topic="${topicId}">${topic.label} ke ${topic.questions.length} questions →</button>`)});document.querySelectorAll('[data-practice-topic]').forEach(b=>b.onclick=()=>{practiceTopic.value=b.dataset.practiceTopic;practiceDifficulty.value='all';renderPractice();setView('practice')})
document.querySelector('#print').onclick=()=>window.print();document.querySelector('#menu').onclick=()=>sidebar.classList.toggle('open');toc.onclick=()=>sidebar.classList.remove('open');window.onscroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.read-progress span').style.width=`${max?100*scrollY/max:0}%`}
